{
 "title": "CPU-mem-Data-nodeexporter",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "CPU ",
   "type": "graph",
   "description": "утилизация CPU для nodeexporter (в процентах, 100-idle",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m]))"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "graph",
   "description": "CPULA 1/5/15",
   "gridPos": { "h": 14, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "node_load1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "node_load5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "node_load15"
    }
   ]
  },
  {
   "title": "количество свободной оперативной памяти",
   "type": "graph",
   "description": "количество свободной оперативной памяти",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job='nodeexporter'}"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе",
   "type": "graph",
   "description": "количество места на файловой системе",
   "gridPos": { "h": 14, "w": 12, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/vda1\", fstype=\"ext4\", instance=\"nodeexporter:9100\", job=\"nodeexporter\", mountpoint=\"/\"}"
    }
   ]
  }
 ]
}